image: python:3.7.6

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install pipenv
          - pipenv install
          - pipenv run pylint --exit-zero *.py
          - pipenv run python -m unittest tests/test_collector.py --locals
